import { Injectable } from "@angular/core";
import { Entity } from "../../entity/model/entity";

/**
 * Shared store of all entities generated by the `GenericDemoDataEngine` (Pass 1).
 *
 * Retained custom-strategy generators inject this store to access engine-generated
 * entities (e.g. Child, School) instead of injecting the now-deleted per-entity
 * generator classes.
 */
@Injectable()
export class DemoEntityStore {
  private readonly store = new Map<string, Entity[]>();

  /** Store the generated entities for an entity type (replaces any previous value). */
  set(entityType: string, entities: Entity[]): void {
    this.store.set(entityType, entities);
  }

  /** Return all generated entities of the given type, or an empty array. */
  get(entityType: string): Entity[] {
    return this.store.get(entityType) ?? [];
  }

  /** Iterate all stored entity types and their entities. */
  entries(): IterableIterator<[string, Entity[]]> {
    return this.store.entries();
  }

  /** Return a flat array of all stored entities across all types. */
  getAll(): Entity[] {
    return Array.from(this.store.values()).flat();
  }

  /** Expose the underlying map for use in DemoValueContext (read-only view). */
  asMap(): Map<string, Entity[]> {
    return this.store;
  }
}
