sudo: required
dist: trusty
language: node_js
branches:
  except:
    - gh-pages
node_js:
  - '12'
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache: npm

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ng lint
  - ng test --watch=false --code-coverage
  - ng build --prod

after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run compodoc

deploy:
  - provider: script
    script: bash docker/publish.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      all_branches: true
  - provider: pages
    skip_cleanup: true
    local_dir: doc/compodoc
    github_token: $GH_REPO_TOKEN
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(master|compodoc)$
