sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9'
env:
  global:
    - CC_TEST_REPORTER_ID=c658ba82647d4ca17571a84f48c1ccf75d6c18e97f0ef0bfaabec3684e2009ae
  matrix:
    - secure: bi/qpNDqs8xosxKaqPH7FsxHljVI579Lt9EUrL7sl1dNAQWA3BW1CSrI7rrSXIe7it632JiuiRzVsDwFFOdTj3DnQKlCaRTM4LWFd1VCWObOcayl4tmb0r552Jwo5AYekKNQ3oeIR5tgQSO3N31CMLQEpVLvO/COFxA6wgdZCZZJGP8lZlk8i4BhhNpie5Zokb/32E+fcahuETHI85+CKbqdPi/jDS06PASCu4cLNYRajK33HVRgSIFgfm/F6xjkDdUwvm7EQZ8CiiSemAm9XKewo6i8K3KuUvOaAXA+vACedfdVhmDEcjwxl5py2FU30WDXxJcWA480NN5pLknYqBNoXkPaGCHuIpiSJIg3uqAzbHQZ+KtxQvmqc9u6dov4R0UuUjBl/UBH1WJ7MnkmAPtikxH9bOFk3TdY7HWol34EjAv4ol99Bpb1f9hJBDHtdbXk+zZMikuBAp8LtAR20LRQg5G+P1AS7n2uG3elDKLtMN7Bv4Sa04iIy/sjbawrfmJ10MiAlkRyGAaVlg/zKgKeQgnbQmHSUUR4br8eqAB9W262uKYn3ilaqDMklO52QIlsrTse08ObUY5jY47eLZ1P9NdHxKsBfI0l7axAaIXSaaoQNJjpbclB8oJJz7MpkuvPMf27EOpFMdJdj6Qun4/60ihTRBkN6/K4y5zVtGM=
    - secure: gOMHgEFJXKZxL7NK6IknMabOqAFYDgLa46bJZpluOCv8+TEBENaSV0p6qm1yns8QdaGFi2RzXqo3AQxDj5YI7C57YyvZNkeUtFD8OXY25Ls/o9YXiVYU89Pca6MJor6PskwIpAw8kuq5i9gOfyLQyKmLwaGwD5KlCw2I2UCcyxUWIlrWgDDQLLTRWjKEt7FVbJjuXiILBSI8hPDJ1IwhmGFc1eJRBMQu3HomyvOK48bT6d5nRpcraPApXROP+X1sTekfDZ3GpiVMEl2dvqITviXoAM0RaWfIy6J45k/LKMYlA4554NbZR4lGM+BiGInXG5iklpXCCbex9wgQ2tpoMqEKhelV7ducsjztmykzAOLH88ArDtlv2O+fqfvgnErkuhg/apWb2nv1e38y5j0Jg7VmQnlQ6W7N16+FYSqvlHJbLRSi74NlWj56cgaSKF7ljqcA76seO6E9VjdU72C/d349gJFWUzlKiuKQ3EaXb3ax2+iJ17JSYy2HSSRS7Nkkkbf/gdp9cVDID3CYayPOt/ojNY2Pu/dr8eA6QSNTjHYIcM2SMmJ800FLUvHEfVNUYkhoy7pVdr+4sPlEnqPgxa4llfxxodu3iXLvf5MWVn8qBC6fSmtnRxF1f1vyTBU86y9IOBx58LXZ/pEAddmlCuzHjvni+WpHatOvTxrqo3U=
services:
  - docker
addons: 
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
script:
  - ng lint
  - ng test --watch=false --code-coverage
  - ng build --prod
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - tar -zcf ${REPO}-${TRAVIS_TAG}.tar.gz dist
deploy:
  - provider: releases
    api_key:
      secure: ODYu9vGivpdmPkGUx61EBO402KT/JzsqA8skNnf7YwR0UMbLqzRLbc7rCd/9QHx/SsRDRyt2y0QuiQtnn5qed0ZiFsvM6Zr59cAKN3PPVy3eYT3O5obnmViiM2bWo+cLee0Ch5vPt5CTOyaus5a56gOB5lGW7nx0v+3rakX9RimewGzvED976ZvCUWiV1K0nX9ZFJVWN6CwlRYWosvjM5FHENMu/NYIDHZA+2ZO4gSwaUFsy65Dwj5dTpJIO1xaVkuxE4LwXnHLoaidtPdmMPlS0BbUIPpfn1LE1im/bSd+0cSJDWc6tVQpIMYu814I8Pf1gCDvVB3pz9iibfOyWCB96MR9J9ywjEbmH6E+/XUJmocxgH7busiKIyRAfbs8JYXALd6GAXVFz5MIfhtJ2L4f+oiPT36kumYbA/WDP17q2lPrRy24KyCfs+f7z9/HHRnEsmRJM52cHe2hk2dd3lzXdeehFA+jPF7ilTNPokpG1fUpgWXcKU6UPgIADbO+u33B17CsdmyGbfOIfTCqdYyS9QMrOyXG8QceXNhUUj9GMCRRV5rz9tJhEKtv5Sl11fpxjsOYq4w1n4n6qwrJEPYztIZJOhN4fDsKUkZNrrg2cIVxbDyZCtfhOvMEexyUYMmtTUnDPHQvS5G74H6j7mvSR8GFRoD6Vcph49CBKNs0=
    file: "${REPO}-${TRAVIS_TAG}.tar.gz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash docker/publish.sh
    on:
      tags: true
