// TODO: remove after rewriting initCategoryFilter() in notes-manager.component
export enum InteractionTypes {
  NONE = "",
  HOME_VISIT = "Home Visit",
  GUARDIAN_TALK = "Talk with Guardians",
  CHILD_TALK = "Talk with Child",
  INCIDENT = "Incident",
  DISCUSSION = "Discussion/Decision",
  VISIT = "School/Hostel Visit",
  PHONE_CALL = "Phone Call",
  COACHING_TALK = "Talk with Coaching Teacher",
  PEER_TALK = "Talk with Peer",
  NEIGHBOUR_TALK = "Talk with Neighbours",
  GUARDIAN_MEETING = "Guardians' Meeting",
  CHILDREN_MEETING = "Children's Meeting",
  DAILY_ROUTINE = "Daily Routine",
  ANNUAL_SURVEY = "Annual Survey",
  EXCURSION = "Excursion/Trip",
  PARTNER_CONTACT = "Contact with other partners (club/NGO/...)",
  RATION_DISTRIBUTION = "Ration Distribution",
}
