import {Injectable} from '@angular/core';
import {DemoDataGenerator} from './demo-data-generator';
import {EntityMapperService} from '../entity/entity-mapper.service';
import {AlertService} from '../alerts/alert.service';
import {AlertDisplay} from '../alerts/alert-display';
import {DemoSchoolGenerator} from './demo-school-generator.service';
import {DemoChildGenerator} from './demo-child-generator.service';

@Injectable()
export class DemoDataService {
  readonly dataProviders: DemoDataGenerator[] = [];

  constructor(private entityMapper: EntityMapperService,
              private alertService: AlertService,
              private demoChildren: DemoChildGenerator,
              private demoSchools: DemoSchoolGenerator,
              // TODO: demo data for ChildSchoolRelations (every child, each year since admission)
              // new DemoChildSchoolRelationGenerator(150, 8),

              // TODO: demo data for Notes (2-10 notes per child)
              // TODO: demo data for AttendanceMonths (every child for last 15 months)
              // TODO: demo data for ASER (from admission till passed or today)
              // TODO: demo data for EducationalMaterials (every child, 2-10 entries for past year)
              // TODO: demo data for HeightWeight (from admission till age 12; every 6 months)

              // TODO: remove database/demo-data.ts
  ) {
    this.dataProviders.push(demoChildren);
    this.dataProviders.push(demoSchools);
  }

  /**
   * Add all entities generated by the registered DemoDataProviders to the Database.
   */
  async publishDemoData() {
    for (const provider of this.dataProviders) {
      for (const entity of provider.entities) {
        try {
          await this.entityMapper.save(entity);
        } catch (e) {
          this.alertService.addWarning(e, AlertDisplay.NONE);
        }
      }
    }
  }
}
