export enum Medium {
  ASSAMESE = "Assamese",
  BENGALI = "Bengali",
  BODO = "Bodo",
  DOGRI = "Dogri",
  ENGLISH = "English",
  GUJARATI = "Gujarati",
  HINDI = "Hindi",
  KANNADA = "Kannda",
  KASHMIRI = "Kashmiri",
  KONKANI = "Konkani",
  MAITHILI = "Maithili",
  MALAYALAM = "Malayalam",
  MARATHI = "Marathi",
  MEITEI = "Meitei",
  NEPALI = "Nepali",
  ODIA = "Odia",
  PUNJABI = "Punjabi",
  SANSKRIT = "Sanskrit",
  SANTALI = "Santali",
  SINDHI = "Sindhi",
  TAMIL = "Tamil",
  TELUGU = "Telugu",
  URDU = "Urdu"
}
