name: Create heroku app for every opened PR
on:
  pull_request:
    types: [opened]

jobs:
  create-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          heroku apps:create ${{ github.head_ref }}-1234
      - name: Post comment on PR
        env:
          PR: ${{ github.ref }}
        run: |
          PR=${PR#refs/*/}
          PR=${PR%/*}
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Aam-Digital/ndb-core/issues/$PR/comments \
          -d '{"body":"Deployed to https://${{ github.head_ref }}-1234.herokuapp.com/"}'
