name: Create heroku app for every opened PR
on:
  pull_request:
    types: [opened]

jobs:
  remove-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          echo ${{ hash(github.head_ref) }}
          echo ${{ hash(github.head_ref) }}
          heroku apps:create ${{ hash(github.head_ref) }}
