name: Create heroku app for every opened PR
on:
  pull_request

jobs:
  create-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          heroku apps:create ${{ github.head_ref }}-1234
