name: Delete heroku app when PR is closed
on:
  pull_request:
    types: [opened]

jobs:
  remove-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          heroku apps:destroy --app ${{ github.head_ref }}-1234 --confirm ${{ github.head_ref }}-1234
