name: Deploy Docker Image to Heroku
on: pull_request

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_SIMON_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: echo ${{ github.head_ref }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-${{ github.head_ref }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

