name: Deploy Docker Image to Heroku
on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build dev image and save it locally
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/pipeline/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          target: builder
          tags: test/run
          outputs: type=local,dest=./img
          build-args: RUN_TESTS=${{ true }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:cache
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
        with:
          coverageLocations: ${{github.workspace}}/img/app/coverage/lcov.info:lcov
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_SIMON_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push prod image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/pipeline/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:cache,mode=max
      - name: Heroku deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          heroku container:login
          docker pull ${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:latest
          docker tag ${{ secrets.DOCKER_SIMON_USERNAME }}/aam-digital-docker-deploy:latest registry.heroku.com/${{ github.head_ref }}-1234/web
          docker push registry.heroku.com/${{ github.head_ref }}-1234/web
          heroku container:release -a ${{ github.head_ref }}-1234 web
