name: i18n - Send translation tokens to POEditor

on:
  push:
    branches:
      # TODO: change to default branch after testing before merge
      - feat/translation-poeditor-integration

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-translations:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: "feat/translation-poeditor-integration"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Extract i18n keys
        run: npm run extract-i18n

      - name: Upload translations to POEditor
        if: env.changed == 'true'
        run: |
          echo "Uploading new terms from ${files}"
          file="src/assets/locale/messages.xlf"
          # see POEditor Upload API: https://poeditor.com/docs/api#projects_upload
          response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
          -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
          -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
          -F "updating=terms" \
          -F "overwrite=1" \
          -F "sync_terms=1" \
          -F "fuzzy_trigger=1" \
          -F "read_from_source=1" \
          -F "file=@${file}")
          status=$(echo $response | jq -r '.response.status')
          if [ "$status" != "success" ]; then
          echo "Error uploading file for $lang: $response"
          exit 1
          fi
