name: i18n - Send translation tokens to POEditor

on:
  push:
    branches:
      # TODO: change to default branch after testing before merge
      - feat/translation-poeditor-integration

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-translations:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: "feat/translation-poeditor-integration"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Extract i18n keys
        run: npm run extract-i18n

      - name: Upload translations to POEditor
        run: |
          file="src/assets/locale/messages.xlf"
          echo "Uploading new terms from ${file}"
          # see POEditor Upload API: https://poeditor.com/docs/api#projects_upload

          languages=("en" "fr" "it" "de")
          for lang in "${languages[@]}"; do
            echo "Uploading ${files[$lang]} for language $lang"
            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
              -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
              -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
              -F "language=$lang" \
              -F "updating=terms_translations" \
              -F "overwrite=1" \
              -F "sync_terms=1" \
              -F "file=@${file}")

            status=$(echo $response | jq -r '.response.status')
            echo "API Response: $response"
            if [ "$status" != "success" ]; then
              echo "Error uploading file for $lang: $response"
              exit 1
            fi
            echo "Waiting for 30 seconds to respect rate limits..."
            sleep 30
          done
