name: Semantic Release
on:
  workflow_dispatch

permissions:
  contents: write  # needed for semantic-release to create tags/releases
  packages: write  # needed for pushing to ghcr.io

jobs:
  pre-releases-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Previous Pre-Releases
        # todo: not maintained anymore, needs replacement
        uses: dev-drprasad/delete-older-releases@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          keep_latest: 0
          delete_tag_pattern: "-master"
          delete_tags: true

  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          branches: |
            [{"name": "master", "prerelease": false}]
          extra_plugins: |
            semantic-release-replace-plugin@1.2.6
            @semantic-release/git
            @semantic-release/github
            semantic-release-slack-bot

  # Re-tag the existing master image with the new stable version
  # (instead of rebuilding, since master image is the same code)
  retag-docker-image:
    needs:
      - release
    if: needs.release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set image names
        run: |
          echo "GHCR_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
          echo "DOCKERHUB_IMAGE=aamdigital/ndb-server" >> "$GITHUB_ENV"
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Re-tag master image with version and stable tags
        run: |
          VERSION="${{ needs.release.outputs.new_release_version }}"
          
          # Re-tag DockerHub images
          echo "Re-tagging ${DOCKERHUB_IMAGE}:master as ${DOCKERHUB_IMAGE}:${VERSION} and ${DOCKERHUB_IMAGE}:stable"
          docker buildx imagetools create -t "${DOCKERHUB_IMAGE}:${VERSION}" "${DOCKERHUB_IMAGE}:master"
          docker buildx imagetools create -t "${DOCKERHUB_IMAGE}:stable" "${DOCKERHUB_IMAGE}:master"
          
          # Re-tag GHCR images
          echo "Re-tagging ${GHCR_IMAGE}:master as ${GHCR_IMAGE}:${VERSION} and ${GHCR_IMAGE}:stable"
          docker buildx imagetools create -t "${GHCR_IMAGE}:${VERSION}" "${GHCR_IMAGE}:master"
          docker buildx imagetools create -t "${GHCR_IMAGE}:stable" "${GHCR_IMAGE}:master"
