name: Pre-Release Cleanup
on:
  push:
    branches:
      - official-release

jobs:
  remove-pre-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Previous Pre-Releases
        # todo: not maintained anymore, needs replacement
        uses: dev-drprasad/delete-older-releases@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          keep_latest: 0
          delete_tag_pattern: master
          delete_tags: true
