name: SetUp
#on:
#  pull_request:
#    types: [opened]
on: pull_request

jobs:
  create-heroku-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          sha = ${{ github.sha }}
          name=${sha:0:30}
          echo ${name}
          heroku apps:create ${name}
      - name: Post comment on PR
        env:
          PR: ${{ github.ref }}
        run: |
          PR=${PR#refs/*/}
          PR=${PR%/*}
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Aam-Digital/ndb-core/issues/$PR/comments \
          -d '{"body":"Deployed to https://${{ github.head_ref }}-test-deployment.herokuapp.com/"}'
