name: SetUp
#on:
#  pull_request:
#    types: [opened]
on: pull_request

jobs:
  create-heroku-app:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "app-name"
    steps:
      - uses: actions/checkout@v2
      - name: Set app name
        shell: bash
        run: |
          name=${{ github.head_ref }}-${{ github.sha }}
          echo "APP_NAME=${sha:0:30}" >> $GITHUB_ENV
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          echo $APP_NAME
          heroku apps:create $APP_NAME
      - name: Post comment on PR
        env:
          PR: ${{ github.ref }}
        run: |
          PR=${PR#refs/*/}
          PR=${PR%/*}
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Aam-Digital/ndb-core/issues/$PR/comments \
          -d '{"body":"Deployed to https://$APP_NAME.herokuapp.com/"}'
