name: SetUp
on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-heroku-app:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "app-name"
    steps:
      - uses: actions/checkout@v2
      - name: Create app name
        run: echo "APP_NAME=test-deployment-pr-${{ github.event.number }}" >> $GITHUB_ENV
      - name: Create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: |
          heroku apps:create ${{ env.APP_NAME }} --region=eu
      - name: Post comment on PR
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Aam-Digital/ndb-core/issues/${{ github.event.number }}/comments \
          -d '{"body":"Deployed to https://${{ env.APP_NAME }}.herokuapp.com/"}'
