name: Semantic Release
on:
  push:
    branches:
      - master
      - official-release
      - semantic_fix

jobs:
  run-semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Only required temporary: https://github.com/cycjimmy/semantic-release-action/issues/159
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          extra_plugins: |
            @google/semantic-release-replace-plugin@1.2.0
            @semantic-release/git
            @semantic-release/github
            semantic-release-slack-bot
