name: Semantic Release
on:
  push:
    branches:
      - master
      - official-release
      - semantic_fix

jobs:
  run-semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          extra_plugins: |
            semantic-release-replace-plugin
            @semantic-release/git
            @semantic-release/github
            semantic-release-slack-bot
